version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: ghcr.io/egikov99/deu-sec-lab-api:latest
    container_name: deu-sec-platform-api
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./reports:/reports
    ports:
      - '8000:8000'
    depends_on:
      - redis

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ghcr.io/egikov99/deu-sec-lab-web:latest
    container_name: deu-sec-platform-web
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - api

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    image: ghcr.io/egikov99/deu-sec-lab-worker:latest
    container_name: deu-sec-platform-worker
    env_file:
      - .env
    volumes:
      - ./reports:/reports
      - ./data:/data
      - ./shared:/app/shared
    depends_on:
      - api
      - redis

  redis:
    image: redis:7-alpine
    container_name: deu-sec-platform-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
